services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - prometheus-storage:/etc/prometheus
    networks:
      - monitoring-network

volumes:
  prometheus-storage: {}

networks:
  monitoring-network:
    external: true 