version: "3.8"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3001:3001'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring-network
volumes:
  grafana-storage: {}

networks:
  monitoring-network:
   external: true